### ISSUE TITLE
Wurst interferes with Mod menu

### ISSUE THREAD

**Issue by muluffel** [Wurst-Imperium/Wurst7#633]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
The _Wurst Options_ Button in the Esc-Menu interferes with the _Mods_ Button which would be there if Wurst wasn't installed. Also it removes the _Give Feedback_ and _Report Bugs_ Button (they aren't necessary for me). Would it maybe be possible to move the button so it won't disable the _Mods_ Button or maybe put them side to side like _Advancements_ and _Statistics_?
Don't hesitate to reach out to me with any further questions.

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Open a Singleplayer world or visit a server
2. Press the Escape button

## Screenshots / Videos (Optional)
How it looks with Wurst:
![2022-04-23_14 31 47](https://user-images.githubusercontent.com/65601356/164895021-82860778-9b87-44ba-9e64-7ed5ab4ff153.png)
How it looks without Wurst:
![2022-04-23_14 33 53](https://user-images.githubusercontent.com/65601356/164895023-7a9c8bca-4f35-4979-8748-e5f5c2305e93.png)

## Crash Report
No Crash report since it's a cosmetic issue, but I'll make one.
https://pastebin.com/Mdtcxh7t

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by songtealake** [comment]
Duplicate of #546, fixed in #550 (still waiting to be merged)

**Comment by Alexander01998** [comment]
Fixed in 9aff6c81bb33ac1555b5930c801aa62a1fac2b42.

**Comment by Bogieloo** [comment]
As of Wurst v7.3 & 7.31, the bug is back and continues to exist
